[package]
name = "orca_whirlpools_core_integration_libm_v0_2"
edition = "2021"

[lib]
path = "../../lib.rs"

[dependencies]
libm = { version = "~0.2" }
orca_whirlpools_core = { path = "../../../core", features = ["floats"] }
