name: Feature Request
description: When you have an idea for an improvement or new feature.
title: "[Feature] "
labels: []
body:
  - type: textarea
  id: details
  attributes:
    label: Details
    description: A clear and concise description of what should be added.
    placeholder: Something needs to be added.
  validations:
    required: true
  - type: textarea
  id: alternatives
  attributes:
    label: Alternatives considered
    description: A clear and concise description of any alternative solutions or features considered.
    placeholder: Other alternatives solutions are not viable.
  validations:
    required: true
