name: 'Push'
description: 'Push changes to the remote repository.'

branding:
  icon: git-branch
  color: blue

inputs:
  branch:
    description: 'Branch to push to'
    required: false
    default: 'main'
  tags:
    description: 'Push tags'
    required: false
    default: 'false'
  message:
    description: 'Commit message (empty means no commit)'
    required: false
  user:
    description: 'Git user name'
    required: false
    default: 'github-actions[bot]'

runs:
  using: "composite"
  steps:
    - name: Setup Git User
      run: |
        git config --global user.name "${{ inputs.user }}"
        git config --global user.email "${{ inputs.user }}@users.noreply.github.com"
      shell: bash
    - name: Git Commit
      if: ${{ inputs.message != '' }}
      run: |
        git add .
        git commit -m "${{ inputs.message }}"
      shell: bash
    - name: Push Changes
      run: |
        git push origin ${{ inputs.branch }}
        if [ ${{ inputs.tags }} = 'true' ]; then
          git push --tags
        fi
      shell: bash
