name: 'Cleanup'
description: 'Remove unnecessary files from the build environment.'

branding:
  icon: trash-2
  color: red

# https://github.com/actions/runner-images/issues/2840#issuecomment-790492173

runs:
  using: "composite"
  steps:
    - name: Remove Unnecessary Files
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      shell: bash
