#!/usr/bin/env bash
set -eo pipefail

# Get the local version from package.json
local_version=$(jq -r ".version" package.json)

# Get the published version from github
published_version=$(curl -s https://orca-so.github.io/whirlpools/ | grep -o '<meta itemprop="version" content="[^"]*"' | cut -d'"' -f4)

function semver { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

# Compare versions
if [ "$(semver $local_version)" -le "$(semver $published_version)" ]; then
  echo "Version $local_version is already published"
  exit 0
fi

# Upload artifact
echo "Publishing version $local_version to gh"
NODE_DEBUG=gh-pages gh-pages -f -d dist -b docs --nojekyll > /dev/null
