name: 'Setup Anchor'
description: 'Sets up an Anchor development environment.'

branding:
  icon: anchor
  color: blue

inputs:
  solana-cluster:
    description: 'The cluster to use for the solana sdk.'
    required: false
    default: 'devnet'
  solana-key:
    description: 'The private key to use for the solana sdk.'
    required: false
  rustc-version:
    description: 'The version of rustc to use.'
    default: 'v1.78.0'
  node-version:
    description: 'The version of node to use.'
    default: 'v22.8.0'
  solana-version:
    description: 'The version of solana to use.'
    default: 'v1.17.25'
  anchor-version:
    description: 'The version of anchor to use.'
    default: 'v0.29.0'

runs:
  using: "composite"
  steps:
    - name: Setup rustc
      run: |
        rust_version=${{ inputs.rustc-version }}
        rustup toolchain install ${rust_version#v}
        rustup default ${rust_version#v}
        rustup component add rustfmt clippy
      shell: bash
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install Solana CLI
      run: |
        wget -qO- "https://release.anza.xyz/${{ inputs.solana-version }}/solana-release-x86_64-unknown-linux-gnu.tar.bz2" | tar -xvj
        echo "$PWD/solana-release/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Anchor CLI
      run: |
        anchor_version=${{ inputs.anchor-version }}
        npm install -g @coral-xyz/anchor-cli@${anchor_version#v}
      shell: bash
    - name: Configure Solana CLI
      run: |
        solana config set --url ${{ inputs.solana-cluster }}
        if [ -z "${{ inputs.solana-key }}" ]; then
          solana-keygen new --no-bip39-passphrase
        else
          echo "${{ inputs.solana-key }}" > ~/.config/solana/id.json
        fi
        solana airdrop 1 || true
      shell: bash
    - name: Log Installed Tools
      run: |
        echo "rustc: $(rustc --version)"
        echo "node: $(node --version)"
        echo "solana: $(solana --version)"
        echo "anchor: $(anchor --version)"
      shell: bash
