[package]
name = "devnet-test"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.0"
solana-sdk = "1.18.0"
solana-program = "1.18.0"
tokio = { version = "1.36.0", features = ["full"] }
serde_json = "1.0.114" 