name: 'Git SSH'
description: 'Setup ssh key for github.'

branding:
  icon: key
  color: green

inputs:
  ssh-key:
    description: 'SSH key'
    required: true
  user:
    description: 'Git user name'
    required: false
    default: 'github-actions[bot]'

runs:
  using: "composite"
  steps:
    - name: Add SSH key
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          echo "${{ inputs.ssh-key }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
      shell: bash
    - name: Setup Git User
      run: |
        git config --global user.name "${{ inputs.user }}"
        git config --global user.email "${{ inputs.user }}@users.noreply.github.com"
      shell: bash
