name: Verify generated clients

on:
  pull_request:
    paths:
      - 'programs/whirlpool/**'
      - 'Anchor.toml'
      - 'codama.*'
      - 'ts-sdk/**'
      - 'rust-sdk/**'
      - '.github/workflows/**'

jobs:
  verify-generated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Anchor toolchain
        uses: ./.github/actions/anchor

      - name: Install deps
        run: yarn install --immutable

      - name: Regenerate IDL
        run: yarn generate:idl

      - name: Generate TS and Rust clients
        run: yarn generate:clients

      - name: Verify no diffs in generated outputs
        run: |
          git diff --exit-code -- \
            ts-sdk/client/src/generated \
            rust-sdk/client/src/generated


